name: Build FOSS
run-name: foss @ ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: Version name
        default: 1.0.0
        required: true
      version_code:
        description: Version code
        default: '100000'
        required: true

concurrency: ${{ github.ref }}

env:
  filename: delta-v${{ inputs.version_name }}-foss

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Export variables
      run: |
        python -u .github/scripts/resolve_paths.py -p >> $GITHUB_ENV

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 18

    - name: Install dependencies
      run: |
        cd ${{ env.sd }}
        sudo pip install -r requirements.txt

    - name: Add new icons
      run: |
        cd ${{ env.sd }}
        python -u add_icons_wrapper.py

    - name: Change version
      run: |
        python - << EOF
        import re

        target = 'app/build.gradle'

        regexp_version_code = re.compile('versionCode (\d+)')
        regexp_version_name = re.compile('versionName "(\d+\.\d+\.\d+(-beta\d+)?)"')

        with open(target, 'r+') as file:
          content = file.read()
          content = re.sub(regexp_version_code, f'versionCode ${{ inputs.version_code }}', content)
          content = re.sub(regexp_version_name, f'versionName "${{ inputs.version_name }}"', content)
          file.seek(0)
          file.write(content)
          file.truncate()
        EOF

    - name: Set custom icons count
      run: |
        drawable_xml=app/src/main/res/xml/drawable.xml
        drawable_lines=$(grep '<item' $drawable_xml | sort)
        summary=$(echo "$drawable_lines" | wc -l)
        amount_all=$(echo "$drawable_lines" | uniq | wc -l)
        amount_new=$(( $summary - $amount_all ))
        shortcut=java/website/leifs/delta/applications/CandyBar.java
        sed -i "s|setCustomIconsCount\(.*\);|setCustomIconsCount\($amount_all\);|" app/src/foss/$shortcut
        sed -i "s|setCustomIconsCount\(.*\);|setCustomIconsCount\($amount_all\);|" app/src/play/$shortcut

    - name: Create changelog
      run: |
        cat << EOF > app/src/main/res/values/changelog.xml
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="changelog_date"></string>
            <string-array name="changelog">
                <item><![CDATA[<font color=#ff837d><item>¯\\_(ツ)_/¯</item></font>]]></item>
            </string-array>
        </resources>
        EOF

    - name: Sort appfilter and drawable
      run: |
        cd ${{ env.sd }}
        python sort_appfilter.py -o
        python sort_drawable.py -o
        cp -fv ${{ env.a1 }} ${{ env.a2 }}
        cp -fv ${{ env.d1 }} ${{ env.a2 }}

    - name: Build APK
      run: |
        bash gradlew assembleFoss

    - name: Move unsigned APK
      run: |
        mv -v app/build/outputs/apk/foss/release/*.apk .

    - name: Sign APK
      uses: kevin-david/zipalign-sign-android-release@main
      id: sign_step
      with:
        alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        releaseDirectory: .

    - name: Move signed APK
      run: |
        mv -v ${{ steps.sign_step.outputs.signedReleaseFile }} ${{ env.filename }}.apk

    - name: Upload signed APK in Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.filename }}
        path: ${{ env.filename }}.apk
        retention-days: 90
