name: Check Conflicts
run-name: conflicts @ ${{ github.sha }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/src/main/rec/drawable-nodpi/**
      - contribs/**

jobs:
  build:
    name: Check Conflicts
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .github/scripts
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo pip install -r requirements.txt

    - name: Add new icons in dry mode
      run: |
        python -u add_icons_wrapper.py
