name: Update Requests
run-name: requests @ ${{ github.sha }}

permissions:
  contents: write

concurrency:
  group: delta

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Requests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .github/scripts
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PA_TOKEN }}

    - name: Install dependencies
      run: |
        sudo pip install -r requirements.txt

    - name: Dump emails
      run: |
        python -u email_dumper.py \
          -u '${{ secrets.EMAIL_ADDRESS }}'  \
          -p '${{ secrets.EMAIL_PASSWORD }}' \
          -r '${{ secrets.EMAIL_FOLDER }}'

    - name: Parse emails
      run: |
        python -u email_parser.py

    - name: Parse requests.yml
      run: |
        python -u requests_parser.py -r

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update requests.yml
        file_pattern: contribs/requests.yml
